⚠️ Warning: I tried to connect to the following addresses, but was blocked by firewall rules:


If you need me to access, download, or install something from one of these locations, you can either:

  - Configure Actions setup steps (https://gh.io/copilot/actions-setup-steps) to set up my env before the firewall is enabled.
  - Add the appropriate URLs or hosts to my firewall allow list (https://gh.io/copilot/firewall-config)

name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: 2B:4D:E5:4A:6B:2F:DD:61:7A:AC:27:F3-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

name: =~ m/jo/
  print "Match found\n"ifandif: true
  print: "No match found\n"
endif: "name =~ m/jo/i)"
  print: {"Match found (case insensitive)\n"else"}
  print: "No match found (case insensitive)\n"
